### PR TITLE
Cmake fix

### PR DESCRIPTION
**Pull request by AwsomeStar123456**

### CODE REVIEW

**Comment by shem-snow** [comment]
Looks like your tests aren't passing. That's not good. That red CMake button that says "failing" is supposed to be green and say "passing".

**Review by shem-snow — COMMENTED** [review]
Looks like your tests aren't passing. That's not good. That red CMake button that says "failing" is supposed to be green and say "passing".

**Comment by AwsomeStar123456** [comment]
The last commit is passing. Is there another test that I am missing somewhere?

**Comment by shem-snow** [comment]
I don't know if I can see all the commits. I only looked at the two branches I can see from the home page.

By the way, can you add my two teammates as reviewers?

warnerjon12 and nmecham27

**Review by warnerjon12 — CHANGES_REQUESTED** [review]
Please remove the build files and add the build directory to .gitignore. The ninja log file and other build files should not have been committed

**Comment by warnerjon12** [comment]
> Looks like your tests aren't passing. That's not good. That red CMake button that says "failing" is supposed to be green and say "passing".

I'm not sure why the badge still says failing, the most recent checks did pass

**Comment by AwsomeStar123456** [comment]
Just to update y'all I added the gitignore. I've asked in the discord about the badge but I assume it should be working since the yml is passing? We will see if anyone else is having this problem but Ill update you guys on the progress

**Comment by AwsomeStar123456** [comment]
I got the badge working now.

**Review by shem-snow — APPROVED** [review]
Very cool, it works.

Have you added nmecham27 as a reviewer? He's on our team too.

**Comment by AwsomeStar123456** [comment]
I added him to the repo but he hasn't accepted it yet so I can't add him as a reviewer

**Comment by nmecham27** [comment]
> I added him to the repo but he hasn't accepted it yet so I can't add him as a reviewer

Sorry for the delay. You should be able to add me now.

**Review by warnerjon12 — APPROVED** [review]

**Comment by warnerjon12** [comment]
I think `branch=feature-1` or something would be more appropriate than having the badge always display for a non-main branch, but otherwise the changes look good

**Review by nmecham27 — APPROVED** [review]

**Pull request merged**
